import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import { DatePipe, PercentPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Post, User } from '../api.service';
@Component({selector:'post-card',standalone:true,imports:[DatePipe,PercentPipe,FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<article [class.misleading]="post().is_misleading"><div class="warning" [hidden]="!post().is_misleading">MISLEADING OR FALSE INFORMATION</div><div class="meta"><span class="avatar">{{post().author.username[0].toUpperCase()}}</span><b>{{post().author.username}}</b><span>·</span><time>{{post().created_at|date:'mediumDate'}}</time>@if(post().category){<span class="tag">{{post().category!.name}}</span>}@if(post().ai_status==='pending'){<span class="pending">AI analysis pending</span>}</div><h2>{{post().title}}</h2><p class="body">{{post().body}}</p><div class="actions"><button (click)="like.emit(post())" [class.liked]="post().liked_by_me" [disabled]="!user()||post().author.id===user()!.id">♥ {{post().like_count}}</button><button (click)="expanded.set(!expanded())">◯ {{post().comment_count}} comments</button></div>
@if(user()?.is_moderator){<aside class="moderation"><b>Moderator review</b>@if(post().ai_moderation_score!==null){<span>AI confidence: {{post().ai_moderation_score|percent}}</span>}@if(post().ai_moderation_rationale){<p>{{post().ai_moderation_rationale}}</p>}<button (click)="moderate.emit(!post().is_misleading)">{{post().is_misleading?'Remove public label':'Mark misleading'}}</button>@if(post().ai_status==='failed'){<button class="quiet" (click)="retryAi.emit()">Retry AI</button>}</aside>}
@if(expanded()){<div class="comments">@for(comment of post().comments;track comment.id){<div><b>{{comment.author.username}}</b><p>{{comment.body}}</p></div>}@if(user()){<div class="comment-form"><input [(ngModel)]="comment" placeholder="Add a thoughtful comment" aria-label="Comment"><button (click)="submitComment()" [disabled]="!comment.trim()">Comment</button></div>}</div>}</article>`})
export class PostCardComponent {readonly post=input.required<Post>();readonly user=input<User|null>(null);readonly like=output<Post>();readonly commentAdded=output<{body:string,done:()=>void}>();readonly moderate=output<boolean>();readonly retryAi=output<void>();readonly expanded=signal(false);comment='';submitComment(){this.commentAdded.emit({body:this.comment.trim(),done:()=>{this.comment='';this.expanded.set(true)}})}}

